#pragma warn unused_var

#include "localization/_localization.dm"
#include "erp/_erp.dm"
#include "character_setup/_character_setup.dm"
#include "dun_world/_dun_world.dm"
#include "races/_races.dm"
#include "gear/_gear.dm"
#include "loadout_panel/_loadout_panel.dm"
#include "automapper/_automapper.dm"
#include "ratwood/_ratwood.dm"
#include "woodcarving/_woodcarving.dm"
#include "ceramics/_ceramics.dm"
#include "neck_amulets/_neck_amulets.dm"
#include "facemasks/_facemasks.dm"
#include "garments/_garments.dm"
#include "snouted_helms/_snouted_helms.dm"
#include "sundries/_sundries.dm"
#include "job_starting_coins.dm"
#include "map_advclass_blacklist.dm"
#include "cyrillic_say_fix.dm"
#include "ear_flick.dm"
#include "upstream_fixes.dm"
#include "tests/_tests.dm"
