#define LOADOUT_PANEL_CATEGORY_ALL "Всё"
#define LOADOUT_PANEL_CATEGORY_DONATOR "Донат"
#define LOADOUT_PANEL_CATEGORY_AZURE "Azure Content"

#define LOADOUT_PANEL_SLOTS_BASE 3
#define LOADOUT_PANEL_SLOTS_TIER1 7
#define LOADOUT_PANEL_SLOTS_TIER2 11
#define LOADOUT_PANEL_SLOTS_TIER3 17
#define LOADOUT_PANEL_SLOTS_TIER4 21
#define LOADOUT_PANEL_SLOTS_TIER5 27
